# Generated by Django 4.1.7 on 2023-03-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_id', models.EmailField(max_length=254, unique=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Modified_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=155)),
                ('password', models.CharField(max_length=155)),
                ('rating', models.FloatField(default=0)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
