# Generated by Django 4.1.7 on 2023-03-24 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('Category', models.PositiveIntegerField(choices=[(1, 'Electronics'), (2, 'Clothing'), (3, 'Books'), (5, 'Beauty'), (4, 'Groceries'), (6, 'Sports')])),
                ('rating', models.FloatField(default=0)),
                ('count', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=5000)),
                ('availability', models.PositiveIntegerField(choices=[(3, 'FEW LEFT'), (2, 'IN STOCK'), (1, 'OUT OF STOCK')])),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='blog.seller')),
            ],
        ),
    ]
