# Generated by Django 4.1.7 on 2023-03-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_order_query_payment_orderproduct_order_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mode',
            field=models.IntegerField(choices=[(1, 'OFFLINE'), (2, 'ONLINE'), (3, 'OTHER')], default=2),
        ),
    ]
