# Generated by Django 4.1.7 on 2023-03-25 14:57

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_payment_card_no_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=blog.models.Order.get_default_request_name, max_length=255),
        ),
    ]
